# Generated by Django 4.2.21 on 2025-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
