# Generated by Django 5.1.4 on 2025-05-31 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_complaint_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_complaints',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.FloatField(
                blank=True,
                null=True,
            ),
        ),
    ]

