# Generated by Django 5.1.4 on 2025-06-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_complaint_assigned_to_complaint_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='sentiment',
        ),
    ]
