# Generated by Django 5.1.4 on 2025-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Include country code e.g. +1234567890', max_length=15, null=True),
        ),
    ]
