# Generated by Django 5.2.8 on 2026-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('non_teaching', 'Non Teaching Faculty'), ('worker', 'Worker'), ('guest', 'Guest'), ('class_teacher', 'Class Teacher'), ('hod', 'HOD'), ('principal', 'Principal'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
